version: '3.1'

services:
  lottery:
    image: 'vdorofeev/lottery:latest'
    container_name: lottery
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USER=user1
      - DB_PASSWORD=1111
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=1111